<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Midnight\Contact\Form\ContactForm $form */
$form = $this->form;
$identity = $this->identity();
$can_edit = ($identity && $identity->getIsAdmin());
?>
<h1><?= $this->translate('Kontakt') ?></h1>
<div class="contact-info">
    <?= $this->wysiwyg($this->text, $this->url('zfcadmin/contact/set-text'), array('condition' => $can_edit)) ?>
</div>
<div class="contact-form">
    <?= $this->wysiwyg($this->formIntro, $this->url('zfcadmin/contact/set-text'), array('condition' => $can_edit)) ?>
    <?= $this->form($form) ?>
</div>
